[2020-07-17T16:45:01.090] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594975501090
err name: ReferenceError
err message: sql is not defined
err stack: ReferenceError: sql is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:14:11)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:63:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at createserver (E:\third\project\server\src\app\controllers\Character.js:82:30)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-17T17:24:41.497] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594977881496
err name: TypeError
err message: resu.append is not a function
err stack: TypeError: resu.append is not a function
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:24:9)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-17T17:52:31.556] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594979551555
err name: TypeError
err message: Cannot read property 'length' of undefined
err stack: TypeError: Cannot read property 'length' of undefined
    at Ta._callee$ (E:\third\project\server\src\utils\/requests.js:50:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tasql (E:\third\project\server\src\utils\requests.js:110:23)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:16:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:65:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-07-17T17:53:50.350] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594979630350
err name: TypeError
err message: Cannot read property 'length' of undefined
err stack: TypeError: Cannot read property 'length' of undefined
    at Ta._callee$ (E:\third\project\server\src\utils\/requests.js:48:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tasql (E:\third\project\server\src\utils\requests.js:108:23)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:16:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:65:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-07-17T17:54:07.551] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594979647551
err name: TypeError
err message: Cannot read property 'length' of undefined
err stack: TypeError: Cannot read property 'length' of undefined
    at Ta._callee$ (E:\third\project\server\src\utils\/requests.js:48:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tasql (E:\third\project\server\src\utils\requests.js:108:23)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:16:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:65:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-07-17T17:54:34.613] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594979674613
err name: TypeError
err message: Cannot read property 'length' of undefined
err stack: TypeError: Cannot read property 'length' of undefined
    at Ta._callee$ (E:\third\project\server\src\utils\/requests.js:50:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tasql (E:\third\project\server\src\utils\requests.js:110:23)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:16:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:65:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-07-17T17:55:02.109] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594979702109
err name: TypeError
err message: Cannot read property 'length' of undefined
err stack: TypeError: Cannot read property 'length' of undefined
    at Ta._callee$ (E:\third\project\server\src\utils\/requests.js:50:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tasql (E:\third\project\server\src\utils\requests.js:110:23)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:16:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:65:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-07-17T17:55:24.888] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/create
request client ip:  ::1
request body: 
{"a":12,"v":[1,2,3,4,5,6]}
response time: 1594979724887
err name: TypeError
err message: Cannot read property 'length' of undefined
err stack: TypeError: Cannot read property 'length' of undefined
    at Ta._callee$ (E:\third\project\server\src\utils\/requests.js:51:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tasql (E:\third\project\server\src\utils\requests.js:111:23)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:16:24)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.test (E:\third\project\server\src\app\service\Character.js:65:22)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
*************** error log end ***************

[2020-07-17T18:03:41.033] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/query
request client ip:  ::1
request body: 
{"a":12,"v":"123456","c":456789}
response time: 1594980221033
err name: TypeError
err message: data.keys is not a function
err stack: TypeError: data.keys is not a function
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:15:26)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:92:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at createserver (E:\third\project\server\src\app\controllers\Character.js:82:30)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-17T18:09:43.533] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/query
request client ip:  ::1
request body: 
{"a":12,"v":"123456","c":456789}
response time: 1594980583533
err name: TypeError
err message: this.bydata is not a function
err stack: TypeError: this.bydata is not a function
    at CharacterService._callee$ (E:\third\project\server\src\app\service\/Character.js:31:20)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:71:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:17:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at createserver (E:\third\project\server\src\app\controllers\Character.js:82:30)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

