[2020-06-30T14:34:23.104] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/permission?username=admin
request client ip:  ::ffff:127.0.0.1
request query:  {"username":"admin"}
response time: 1593498863103
err name: JsonWebTokenError
err message: verify must be called asynchronous if secret or public key is provided as a callback
err stack: JsonWebTokenError: verify must be called asynchronous if secret or public key is provided as a callback
    at module.exports (E:\third\fancy-game-master\server\node_modules\jsonwebtoken\verify.js:83:19)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at verify (internal/util.js:296:12)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:15:21)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at E:\third\fancy-game-master\server\src\middleware\auth.js:67:17
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (E:\third\fancy-game-master\server\src\middleware\/permission.js:91:17)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at E:\third\fancy-game-master\server\src\middleware\/permission.js:78:2
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/interceptor.js:77:10)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
*************** error log end ***************

[2020-06-30T14:44:43.455] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/permission?game=%E5%88%BA%E5%AE%A2%E5%A5%91%E7%BA%A6
request client ip:  ::1
request query:  {"game":"刺客契约"}
response time: 1593499483454
err name: JsonWebTokenError
err message: invalid token
err stack: JsonWebTokenError: invalid token
    at module.exports (E:\third\fancy-game-master\server\node_modules\jsonwebtoken\verify.js:75:17)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at verify (internal/util.js:296:12)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:15:21)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at E:\third\fancy-game-master\server\src\middleware\auth.js:67:17
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee4$ (E:\third\fancy-game-master\server\src\middleware\/permission.js:91:17)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at E:\third\fancy-game-master\server\src\middleware\/permission.js:78:2
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/interceptor.js:77:10)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
*************** error log end ***************

[2020-06-30T18:25:23.088] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/permission
request client ip:  ::1
request query:  {}
response time: 1593512723088
err name: TypeError
err message: _baseDao2.default.findSqlByParamsToList is not a function
err stack: TypeError: _baseDao2.default.findSqlByParamsToList is not a function
    at _callee$ (E:\third\fancy-game-master\server\src\app\dao\/Components.js:5:23)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _callee$ (E:\third\fancy-game-master\server\src\app\controllers\/user.js:17:24)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at findUser (E:\third\fancy-game-master\server\src\app\controllers\user.js:82:26)
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:351:31)
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:19:9)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
*************** error log end ***************

[2020-06-30T18:34:25.799] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/permission
request client ip:  ::1
request query:  {}
response time: 1593513265799
err name: ReferenceError
err message: resolve is not defined
err stack: ReferenceError: resolve is not defined
    at E:\third\fancy-game-master\server\src\app\dao\/Components.js:7:3
    at tryCatcher (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\fancy-game-master\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

