[2020-07-01T14:49:22.279] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/qf
request client ip:  ::1
request query:  {}
response time: 1593586162279
err name: TypeError
err message: _requests2.default.findid is not a function
err stack: TypeError: _requests2.default.findid is not a function
    at _callee2$ (E:\third\fancy-game-master\server\src\app\controllers\/user.js:31:27)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at qf (E:\third\fancy-game-master\server\src\app\controllers\user.js:120:20)
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:351:31)
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:19:9)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-01T14:51:10.800] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/qf
request client ip:  ::ffff:127.0.0.1
request query:  {}
response time: 1593586270800
err name: TypeError
err message: _requests2.default.findid is not a function
err stack: TypeError: _requests2.default.findid is not a function
    at _callee2$ (E:\third\fancy-game-master\server\src\app\controllers\/user.js:31:27)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at qf (E:\third\fancy-game-master\server\src\app\controllers\user.js:120:20)
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:351:31)
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:19:9)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-01T14:55:43.111] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/qf
request client ip:  ::ffff:127.0.0.1
request query:  {}
response time: 1593586543111
err name: ReferenceError
err message: talist is not defined
err stack: ReferenceError: talist is not defined
    at Ta._callee2$ (E:\third\fancy-game-master\server\src\utils\/requests.js:76:10)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-01T14:56:17.397] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/qf
request client ip:  ::ffff:127.0.0.1
request query:  {}
response time: 1593586577396
err name: ReferenceError
err message: talist is not defined
err stack: ReferenceError: talist is not defined
    at Ta.tarequest (E:\third\fancy-game-master\server\src\utils\/requests.js:76:4)
    at _callee2$ (E:\third\fancy-game-master\server\src\app\controllers\/user.js:31:27)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at qf (E:\third\fancy-game-master\server\src\app\controllers\user.js:120:20)
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:351:31)
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:19:9)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-01T14:58:51.175] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/qf
request client ip:  ::ffff:127.0.0.1
request query:  {}
response time: 1593586731175
err name: ReferenceError
err message: a is not defined
err stack: ReferenceError: a is not defined
    at Ta._callee2$ (E:\third\fancy-game-master\server\src\utils\/requests.js:76:15)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Ta.<anonymous> (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Ta.tarequest (E:\third\fancy-game-master\server\src\utils\requests.js:137:27)
    at _callee2$ (E:\third\fancy-game-master\server\src\app\controllers\/user.js:31:27)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at qf (E:\third\fancy-game-master\server\src\app\controllers\user.js:120:20)
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\fancy-game-master\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\fancy-game-master\server\node_modules\koa-router\lib\router.js:351:31)
    at next (E:\third\fancy-game-master\server\node_modules\koa-compose\index.js:42:32)
    at _callee$ (E:\third\fancy-game-master\server\src\middleware\/auth.js:19:9)
*************** error log end ***************

[2020-07-01T18:16:07.221] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/user/qf
request client ip:  ::1
request query:  {}
response time: 1593598567220
err name: TypeError
err message: result.then is not a function
err stack: TypeError: result.then is not a function
    at _callee2$ (E:\third\fancy-game-master\server\src\app\controllers\/user.js:32:10)
    at tryCatch (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\fancy-game-master\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\fancy-game-master\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

