[2020-08-03T16:43:13.418] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1596444193417
err name: SequelizeDatabaseError
err message: column "字段名（策划）" does not exist
err stack: SequelizeDatabaseError: column "字段名（策划）" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T16:59:23.096] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"1","gameid":"1"}
response time: 1596445163095
err name: TypeError
err message: Cannot read property 'path' of undefined
err stack: TypeError: Cannot read property 'path' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:22)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:134:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:97:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T16:59:43.116] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445183115
err name: TypeError
err message: Cannot read property 'path' of undefined
err stack: TypeError: Cannot read property 'path' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:22)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:134:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:97:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:00:24.089] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445224088
err name: TypeError
err message: Cannot read property 'file' of undefined
err stack: TypeError: Cannot read property 'file' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:27)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:00:50.263] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445250263
err name: TypeError
err message: Cannot read property 'images' of undefined
err stack: TypeError: Cannot read property 'images' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:27)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:01:05.012] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445265012
err name: ReferenceError
err message: path is not defined
err stack: ReferenceError: path is not defined
    at filePath (E:\third\project\server\src\app\service\/gm-announcement.js:18:19)
    at new Promise (<anonymous>)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:15:25)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-08-03T17:01:29.035] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445289035
err name: TypeError
err message: Cannot read property 'path' of undefined
err stack: TypeError: Cannot read property 'path' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:14:22)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:02:14.615] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445334615
err name: ReferenceError
err message: path is not defined
err stack: ReferenceError: path is not defined
    at filePath (E:\third\project\server\src\app\service\/gm-announcement.js:18:19)
    at new Promise (<anonymous>)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:15:25)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-08-03T17:02:16.115] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445336115
err name: ReferenceError
err message: path is not defined
err stack: ReferenceError: path is not defined
    at filePath (E:\third\project\server\src\app\service\/gm-announcement.js:18:19)
    at new Promise (<anonymous>)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:15:25)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

